# prettier-ignore
version: '3.6'
services:
  knoperator:
    image: knoperator:latest
    build: .
    command: ["start", "-l", "trace"] # use this command to run in trace mode
    environment:
      - "KNOPERATOR_DATA_DIR=/data/database"

      - "KNOPERATOR_K8S_DEFAULT_IMAGE_PULL_POLICY=${KNOPERATOR_K8S_DEFAULT_IMAGE_PULL_POLICY}"
      - "KNOPERATOR_MQ_URI=${KNOPERATOR_MQ_URI}"

      # define either:
      - "KNOPERATOR_MQ_CREDS_PATH=${KNOPERATOR_MQ_CREDS_PATH}"

      # or define these: (read the data from the mq.creds manually)
      - "KNOPERATOR_MQ_JWT=${KNOPERATOR_MQ_JWT}"
      - "KNOPERATOR_MQ_USEED=${KNOPERATOR_MQ_USEED}"
    volumes:
      - "./data/database:/data/database"
      - "./mq.creds:/mq.creds"
