apiVersion: apps/v1
kind: Deployment
metadata:
  name: knoperator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: knoperator
  template:
    metadata:
      labels:
        name: knoperator
    spec:
      serviceAccountName: knoperator
      containers:
        - name: knoperator
          image: knoperator
          imagePullPolicy: IfNotPresent
          args:
            - start
            - -l
            - trace
          env:
            - name: knoperator_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: knoperator_K8S_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: knoperator_MQ_URI
              value: ws://192.168.2.102:9222
            - name: knoperator_MQ_JWT
              valueFrom:
                secretKeyRef:
                  name: knoperator-mq-jwt
                  key: jwt
            - name: knoperator_MQ_USEED
              valueFrom:
                secretKeyRef:
                  name: knoperator-mq-useed
                  key: useed
            - name: knoperator_K8S_INCLUSTER
              value: "true"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
